package com.springtraining.furnitureshop.util;

public class Attributes {
    public static final String ERRORS = "errors";
    public static final String ORDER_CREATED = "orderCreated";
    public static final String ORDER_ITEMS = "orderItems";
    public static final String ORDERS = "orders";
    public static final String ORDERS_BEAN = "ordersBean";
    public static final String PAGE_NUMBERS = "pageNumbers";
    public static final String USERS_SERVICE = "usersService";
    public static final String CAPTCHA_SERVICE = "captchaService";
    public static final String CATEGORIES_SERVICE = "categoriesService";
    public static final String PRODUCERS_SERVICE = "producersService";
    public static final String PRODUCTS_SERVICE = "productsService";
    public static final String ORDERS_SERVICE = "ordersService";
    public static final String REGISTRATION_BEAN = "registrationBean";
    public static final String PRODUCT_BEAN = "productBean";
    public static final String CAPTCHA = "captcha";
    public static final String CAPTCHA_MAP = "captchaMap";
    public static final String CAPTCHA_ID = "captchaID";
    public static final String CAPTCHA_PROVIDER = "captchaProvider";
    public static final String PAGE_GENERATION_TIME = "pageGenerationTime";
    public static final String CREDENTIALS = "credentials";
    public static final String USER = "user";
    public static final String AVATAR_SIZE = "avatarSize";
    public static final String PAGE_SIZE = "pageSize";
    public static final String SORT_TYPE = "sortType";
    public static final String PRODUCTS = "products";
    public static final String PRODUCT = "product";
    public static final String COUNT_PRODUCTS = "countProducts";
    public static final String URL = "url";
    public static final String CART = "shoppingCart";
    public static final String CART_SERVICE = "cartService";
    public static final String QUERY_STRING = "queryString";
    public static final String SECURITY_FILE = "securityFile";
    public static final String SECURITY_MANAGER = "securityManager";
    public static final String BAN = "ban";
    public static final String UNBAN_DATE = "unbanDate";
    public static final String TITLE = "title";
    public static final String REFERRER = "referrer";
}
