spring:
  datasource:
    url: jdbc:mysql://localhost:3306/furniture_shop
    username: root
    password: admin
  jpa:
    show-sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  endpoints:
    web:
      exposure:
        include: "*"


furnitureshop:
  localization:
    defaultLocale: en-US
    cookieMaxAge: 30
  user:
    maxLoginAttempts: 3
    banDuration: 60
  avatar:
    directory: "avatars/"
    max-file-size: 5MB
  products:
    paginationRange: 4
    pageSizes:
      - 5
      - 10
      - 25
      - 100

    defaults:
      page: 1
      size: 5
      sortOrder: desc
      sortField: price
logging:
  level:
    com.springtraining.furnitureshop: TRACE