spring:
  datasource:
    url: jdbc:mysql://localhost:3306/furniture_shop
    username: root
    password: admin
management:
  endpoints:
    web:
      exposure:
        include: "*"
furnitureshop:
  localization:
    defaultLocale: en-US
    cookieMaxAge: 30
  user:
    maxLoginAttempts: 3
    banDuration: 60
  products:
    paginationRange: 4
    pageSizes:
      - 5
      - 10
      - 25
      - 100

    defaults:
      page: 1
      size: 5
      sortOrder: desc
      sortField: price